CC = gcc
LIB = myftp.c
LIBS ?= -lpthread

all: server client

server: server.c ${LIB}
	${CC} -o server server.c ${LIB} ${LIBS}

client: client.c ${LIB}
	${CC} -o client client.c ${LIB} 

clean:
	rm server
	rm client	
