CC = gcc
LIB = -lsocket -lnsl -lpthread
LIBS = myftp.c

all: server client

server: server.c
	${CC} -o server server.c ${LIBS} ${LIB} -std=gnu99

client: client.c
	${CC} -o client client.c ${LIBS} ${LIB} -std=gnu99

clean:
	rm server
	rm client
