CC = gcc
LIB = myftp.c
LIBS ?= -lpthread

all: server client

server: server.c ${LIB}
	${CC} -o server server.c ${LIB} ${LIBS} -std=gnu99

client: client.c ${LIB}
	${CC} -o client client.c ${LIB} -std=gnu99

clean:
	rm server
	rm client	
