CC = gcc
LIB = myftp.c
LILBS ?= -lsocket -lnsl

all: server client

server: server.c
	${CC} -o server server.c ${LIB} ${LIBS}

client: client.c
	${CC} -o client client.c ${LIB} ${LIBS}

clean:
	rm server
	rm client
